### ISSUE TITLE
Protocole princeton

### ISSUE THREAD

**Issue by jamesboss112233** [DarkFlippers/flipperzero-subbrute#19]
Brute forcing princeton 24 bits 
433mhz is it possible ? And how ? 🤔

**Comment by xMasterX** [comment]
Only specific remotes that are using dip switches, we already have this in the app

or you can use your file via BF Existing dump
then you can select two or 4 bytes to bruteforce
but not 24!
24 bit bruteforce will take 800+ hours, do you want to wait ~800 hours?

**Comment by jamesboss112233** [comment]
I'm new, I wanted to try to brute force my house bell. I know the security
protocol but I didn't know the BF application. Thank you for your help
anyway. Isn't there a way to reduce the possibilities?

**Comment by jamesboss112233** [comment]
Can you explain how to use the BF existing dump because I don't quite understand the maneuver. I select up to x6 and I launch but it doesn't find anything...

**Comment by jamesboss112233** [comment]
It's impossible. I understood 😪
