### ISSUE TITLE
Chamberlain 8 bit code drops bit 3

### ISSUE THREAD

**Issue by FalcoGer** [DarkFlippers/flipperzero-subbrute#2]
An 8 bit code should have 8 bits encoded in the message. However the 8 bit chamberlain code has only 7 bits encoded. Bit 3 is dropped.

When recording a message for 0/255, it is exactly the same as 4/255.

![image](https://user-images.githubusercontent.com/16250196/201444120-19137d49-55d5-4d09-a3ee-f4a679c97652.png)

What's more, 9bit and 7bit encoded messages have 11 symbols each. But the 8 bit encoded messages have only 10 symbols.

![image](https://user-images.githubusercontent.com/16250196/201445083-7d335427-38b9-41b9-ac5a-512f986c46ab.png)

I believe the correct encoding is as such:

```
Symbols:
0  -  0111
1  -  0011
S  -  0001
```

```
9bit: S D8 D7 D6 D5 D4 D3 D2 D1 D0 S

Probably either of those:
8bit: S D7 D6 D5 D4 D3 D2  S D1 D0 S
8bit: S D7 D6 D5 D4 D3 D2 D1  S D0 S

7bit: S D6 D5 D4 D3 D2 D1  S  S D0 S
```

However currently the encoding is as such

```
9bit: S D8 D7 D6 D5 D4 D3 D2 D1 D0 S
8bit:    S D7 D6 D5 D4 D3  S D1 D0 S, D2 dropped from output
7bit: S D6 D5 D4 D3 D2 D1  S  S D0 S
```

**Comment by xMasterX** [comment]
It just starts from 0005/0255
0005 = key: 0x001 - DIP: 00000x10
0255 = key: 0x0FB - DIP: 11111x11

How you tested it, did you run all your tests on roguemaster firmware?

**Comment by FalcoGer** [comment]
What do you mean it starts from 0005? Yes, I'm running RM.
`00000x10` is 7 bits, not 8 bits.
The actual 7 bit key is 7 bits and the actual 9 bit key is 9 bits. Why would the "8 bit" key have 7 bits and ignore the 3rd dip switch? That'd be insane.

**Comment by derskythe** [comment]
> Yes, I'm running RM.

Please try on Unleashed. This app is not tested on RM

**Comment by FalcoGer** [comment]
Same thing on unleashed. Bit 3 is dropped for 8 bit codes. Everything is the exact same as described above.

**Comment by derskythe** [comment]
I tried to test using 2 flippers. On one with a brute force, on the other, reading and all signals were exactly repeated in ascending order of the digit.
Perhaps the effect you're talking about comes from the protocol itself.
Also in the program, you can record individual signals of interest to you and try to repeat them.
I also note that in some protocols there are exceptional combinations of switches that do not occur and can be skipped.

If you have a device that does not correctly respond to the received code, then we can make the necessary changes. But only if you can confirm that the gate is not working correctly with the current algorithm

**Comment by derskythe** [comment]
My bad I tested in 7-bit mode, but in 8-bit I found issue.

**Comment by FalcoGer** [comment]
I do not have a garage door. I simply found an issue trying to reverse engineer the protocols with my SDR. The issue is that bit 3 is ignored. Since I assume that in a real garage door that bit would not be ignored, I figured it must be a bug.

**Comment by derskythe** [comment]
According official answer I can just start from 5

https://github.com/flipperdevices/flipperzero-firmware/issues/2006

**Comment by Skorpionm** [comment]
No, you can’t) again, there will be repetitions. you need to remove the unused bit from the enumeration

**Comment by derskythe** [comment]
> No, you can’t) again, there will be repetitions. you need to remove the unused bit from the enumeration

Да, я просто допилю пропуски, чтобы было меньше времени полный перебор

**Comment by FalcoGer** [comment]
Why are we talking russian now?
Bit 3 is ignored in the current implementation. If it is correct, then there is a bug in the protocol or it's implementation in the garage doors. I doubt that is the case.
if you send 1111 1111 (0xFF), you will receive 1111 1011 (0xFB).
In fact, any value you sent will have bit 3 as a 0 on the receiver, because the protocol, as it currently stands, uses 7 bits only.

I don't know how many different ways I have to explain this. An 8 bit key should have 8 data bits, but only 7 are sent in 10 symbols, 3 of which are markers (leaving 7 for data). The missing bit is bit number 3.

**Comment by FalcoGer** [comment]
If this is in fact the way it's supposed to be, then you can brute force the 7 bits that matter. Either you skip 8 values every 8 values, or you brute force 7 bits and left shift from bit 3. The easiest is probably to have two loops, one to brute force the two lower bits and one for the 5 upper bits, then left shift the upper bits by 3 and OR them together. to get your 8 bit code.

**Comment by FalcoGer** [comment]
> Because we both understand this language.

It would be nice if everyone can participate in discussions.

> Let me explain something, at the application level, all I can do is generate numbers and pass them to the firmware.

That is what I just proposed. If this is how the protocol actually works, then generate the numbers to skip duplicate outputs. I proposed a few methods with which to achieve that.

**Comment by m0xsec** [comment]
> I feel like I'm going crazy. How can I explain it so people understand me?

@FalcoGer I am getting the same behavior, this is very strange.

> No, you can’t) again, there will be repetitions. you need to remove the unused bit from the enumeration

This would be the best path forward based on my testing.


> > Because we both understand this language.
> 
> It would be nice if everyone can participate in discussions.

English is not the only language :)

**Comment by FalcoGer** [comment]
Why is this closed? Did you implement the skipping when bit 3 is high, or was there a bug with the protocol that has been fixed?

**Comment by derskythe** [comment]
@FalcoGer not yet. This bug is low priority
