### ISSUE TITLE
Holtek 12 bit AM issue

### ISSUE THREAD

**Issue by nobann** [DarkFlippers/flipperzero-subbrute#23]
Hi, 
congrats for the great work.
Just tried the bruteforce 3.6 version on my garage door 
I copied the remote normally it's using static code. it shows holtek 12 AM 433 code 0x556.
Then tried your bruteforce app on unleashed latest version and chosed holtek 12 am 433 ran all the sequence and the door didnt open .

**Comment by xMasterX** [comment]
send your file that you saved from subghz->read

**Comment by nobann** [comment]
hello thaks for your quick answer 
here is the sub file 👍 

Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: Holtek_HT12X
Bit: 12
Key: 00 00 00 00 00 00 05 56
TE: 364

**Comment by xMasterX** [comment]
<img width="247" alt="Screenshot 2023-06-25 at 21 35 44" src="https://github.com/DarkFlippers/flipperzero-subbrute/assets/10697207/6fe3dc52-0252-4798-9470-c67cb299d3cb">

So all is clear, your remote uses different TE, this is main signal encoding timing unit
Its not possible to find one universal TE for all, its all different from one manufacturer to another
But option to configure TE may be added in a future

**Comment by xMasterX** [comment]
Hi, @gid9798 made option to change TE, try new 3.7 version
