### ISSUE TITLE
PMA51XX/PMA71xx support 

### ISSUE THREAD

**Issue by mgrybyk** [DarkFlippers/flipperzero-subbrute#30]
Hello,

Is it possible to add support for PMA7105?

Links:
- https://www.digikey.com/en/products/detail/rochester-electronics-llc/PMA7105/12127669
- https://eu.mouser.com/datasheet/2/196/PMA71xx_PMA51xx_Function_Library_Guide_V1_5-2322507.pdf

I have the key and I can provide with saved dumps. 

Thanks!

**Comment by derskythe** [comment]
Hi @mgrybyk 
looks very tricky for such a small app. 
As I understand it, there are rolling codes, unfortunately this application does not support such codes and will not support in the future
