### ISSUE TITLE
NULL pointer exception on existing dump BF save

### ISSUE THREAD

**Issue by oleynikd** [DarkFlippers/flipperzero-subbrute#49]
Hi Flippers,
I'm getting a NULL pointer exception when I try to save a key from BF from an existing dump. Please check the video. In this case I'm using NICE 12 433 as a starting dump file:
```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: Nice FLO
Bit: 12
Key: 00 00 00 00 00 00 0A 6F
```

FW: [unlshd-066e](https://github.com/DarkFlippers/unleashed-firmware/releases/tag/unlshd-066)
APP: v3.9.X [subghz_bruteforcer.fap.zip](https://github.com/DarkFlippers/flipperzero-subbrute/files/13654589/subghz_bruteforcer.fap.zip)

https://github.com/DarkFlippers/flipperzero-subbrute/assets/3976868/e43654db-182d-4c7e-b708-187ca6c2606d

**Comment by derskythe** [comment]
@oleynikd please check fixed version: 
https://github.com/DarkFlippers/flipperzero-subbrute/releases/tag/v3.10.0

**Comment by oleynikd** [comment]
@derskythe  Tested version [v3.10.1](https://github.com/DarkFlippers/flipperzero-subbrute/releases/tag/v3.10.1) - problem solved. Thanks.
