### ISSUE TITLE
"Doitrand" Protocol & Restaurant pagers

### ISSUE THREAD

**Issue by Cynemosniper** [DarkFlippers/flipperzero-subbrute#5]
Hello, in France the "Doitrand" brand is very present, would it be possible to add this protocol to the application? :)
Also could you add restaurant pager bruteforce as well ?

**Comment by derskythe** [comment]
Hi, I don't see such pagers.
Only in China restraint saw device worked on Princeton.
Unfortunately, key is too big to brute.
You can use such schema:
1. Receive sample of real device
2. Use last option in menu to select file
3. Bruteforcing trying to brute nearest values
4.
