### ISSUE TITLE
Add 318 MHz to 9-bit (Chamberlain and/or Linear)

### ISSUE THREAD

**Issue by hotdjdave** [DarkFlippers/flipperzero-subbrute#73]
Add 318 MHz to 9-bit (Chamberlain and/or Linear -- I think either would work).  In the USA, most of the 9-bit gate/garage opener/remotes use 318 MHz.

Thanks.

**Comment by hotdjdave** [comment]
What happened?  Is this something that can be done?  Thanks.

**Comment by derskythe** [comment]
@hotdjdave Hi, please check [new release](https://github.com/DarkFlippers/flipperzero-subbrute/releases/tag/v3.12.0)

**Comment by hotdjdave** [comment]
> @hotdjdave Hi, please check [new release](https://github.com/DarkFlippers/flipperzero-subbrute/releases/tag/v3.12.0)

Awesome!  Thank you.
