### ISSUE TITLE
subghz_bruteforcer_icons.h

### ISSUE THREAD

**Issue by aaronryank** [DarkFlippers/flipperzero-subbrute#79]
I'm at my wit's end. Attempting to build this application with `fbt` fails due to the nonexistence of `subghz_bruteforcer_icons.h`.

In helpers/gui_top_button.c: `#include <subghz_bruteforcer_icons.h>`

In subbrute_i.h: `#include <subghz_bruteforcer_icons.h>`

I cannot find this file anywhere - I have searched through all Flipper Zero firmware, possibly relevant GitHub repositories, and anywhere else on the Internet I could crawl through. Where on earth is this file?

**Comment by derskythe** [comment]
Hello @aaronryank, 
this file is generated after you run:
```shell
./fbt fap_dist
```

[See OFW documentation](https://developer.flipper.net/flipperzero/doxygen/apps_on_sd_card.html)
